language: node_js
node_js:
  - "9"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: QUALITY=yes
    - os: linux
      dist: precise
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx
    
branches:
  only: master
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update

before_script:
    - travis_retry npm install
    - travis_retry npm install coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint
    - travis_retry npm install -g coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint
    - travis_retry sudo apt-get install tinyproxy 
    - tinyproxy

script:
    - travis_retry npm run test
    - travis_retry npm run lint  

after_success:
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run cover; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run coveralls; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codecov; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codacy; fi
