sudo: required
dist: trusty
language: node_js
node_js:
  - "9"

branches:
  only: master

before_script:
    - npm install
    - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/node-binance-api/gh-travis/node-binance-api-test.js -O node-binance-api-test.js
    - npm install -g coveralls
    - npm install -g istanbul

script:
    - node node-binance-api-test.js
    - istanbul cover node-binance-api-test.js && cat ./coverage/lcov.info | coveralls

