language: node_js
node_js:
  - "9"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx
    
branches:
  only: master
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update

before_script:
    - npm install
    - travis_retry npm install
    - travis_retry npm install coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint
    - travis_retry npm install -g coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint

script:
    - npm run test
    - npm run lint  

after_success:
    - if [[ $TRAVIS_OS_NAME != "linux" ]]; then npm run cover; fi
    - if [[ $TRAVIS_OS_NAME != "linux" ]]; then npm run coveralls; fi
    - if [[ $TRAVIS_OS_NAME != "linux" ]]; then npm run codecov; fi
    - if [[ $TRAVIS_OS_NAME != "linux" ]]; then npm run codacy; fi
