language: node_js
node_js:
  - "9"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: QUALITY=yes
    - os: linux
      dist: precise
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx
    
branches:
  only: master
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update

before_script:
    - ssh-keygen -f id_rsa -t rsa -N ''
    - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
    - chmod 600 ~/.ssh/*
    - ssh -f -D 9999 -q -N `whoami`@localhost
    - travis_retry git clone -b gh-pages https://git@$GH_REPO_REF docs
    - travis_retry npm install
    - travis_retry npm install coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint jsdoc
    - travis_retry npm install -g coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint jsdoc
    - travis_retry sudo apt-get install tinyproxy curl
    - tinyproxy
    - travis_retry curl -v -I --proxy socks://127.0.0.1:9999 https://www.google.com    

script:
    - travis_retry npm run test
    - export socks_proxy=http://127.0.0.1:9999
    - travis_retry npm run test
    - unset socks_proxy
    - travis_retry npm run lint  

after_success:
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run cover; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run coveralls; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codecov; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codacy; fi
    - if [[ $QUALITY == "yes" ]]; then mv docs/docs.sh .; cd docs; rm -rvf ./*; mv ../docs.sh .; chmod +x docs.sh; ./docs.sh; fi    
    
env:
  global:
    - GH_REPO_NAME: node-binance-api
    - GH_REPO_REF: github.com/jaggedsoft/node-binance-api.git
    - JSDOC_FILES: $TRAVIS_BUILD_DIR/node-binance-api.js
