sudo: required
dist: trusty
language: node_js
node_js:
  - "9"

branches:
  only: master

before_script:
    - npm install
    - travis_retry wget https://raw.githubusercontent.com/jaggedsoft/node-binance-api/gh-travis/node-binance-api-test.js -O test.js
    - travis_retry npm install
    - travis_retry npm install coveralls istanbul mocha chai 
    - travis_retry npm install -g coveralls istanbul mocha chai 

script:
    - npm run test

after_success:
    - npm run cover
    - npm run coveralls
