language: node_js
node_js:
  - "9"

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: QUALITY=yes
    - os: linux
      dist: precise
      sudo: required
    - os: osx
      osx_image: xcode7.2
  allow_failures:
    - os: osx
    
branches:
  only: master
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update

before_script:
    - travis_retry git clone -b gh-pages https://git@$GH_REPO_REF
    - travis_retry npm install
    - travis_retry npm install coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint jsdoc
    - travis_retry npm install -g coveralls istanbul mocha chai codecov codacy-coverage mocha-lcov-reporter eslint jsdoc
    - travis_retry sudo apt-get install tinyproxy curl
    - tinyproxy
    - travis_retry curl -v -I --proxy http://127.0.0.1:8888 https://www.google.com    

script:
    - travis_retry npm run test
    - travis_retry npm run lint  

after_success:
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run cover; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run coveralls; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codecov; fi
    - if [[ $QUALITY == "yes" ]]; then travis_retry npm run codacy; fi
    - if [[ $QUALITY == "yes" ]]; then 
         cd $GH_REPO_NAME; 
         git config --global push.default simple; 
         git config user.name "Travis CI";    
         git config user.email "travis@travis-ci.org"; 
         rm -rf *
         echo "" > .nojekyll;
         cat <<EOF > README.md
            # php-binance-api
            PHP Binance API is an asynchronous PHP library for the Binance API designed to be easy to use.
            https://github.com/binance-exchange/php-binance-api
            ## Documentation
            You are looking at the doxygen documentation branch, this is auto generated
            You can donwload a copy of the documentation using the following url:
            [download](https://github.com/jaggedsoft/php-binance-api/archive/gh-pages.zip)
         EOF
         jsdoc --debug --verbose ../node-binance-api.js -d .; 
         git add --all
         git commit -m "Deploy code docs to GitHub Pages Travis build: ${TRAVIS_BUILD_NUMBER}" -m "Commit: ${TRAVIS_COMMIT}"
         git push --force "https://${GH_REPO_TOKEN}@${GH_REPO_REF}" > /dev/null 2>&1
      fi    
    
env:
  global:
    - GH_REPO_NAME: node-binance-api
    - GH_REPO_REF: github.com/jaggedsoft/node-binance-api.git
    - JSDOC_FILES: $TRAVIS_BUILD_DIR/node-binance-api.js
